// build.js - Injects Vercel Environment Variables into env.js for production static hosting
const fs = require('fs');

const envContent = `/**
 * Auto-generated by Vercel Build Step from Environment Variables
 */
window.ENV = {
  GOOGLE_APPS_SCRIPT_URL: "${process.env.GOOGLE_APPS_SCRIPT_URL || ''}",
  SPREADSHEET_ID: "${process.env.SPREADSHEET_ID || ''}",
  GOOGLE_DRIVE_FOLDER_LINK: "${process.env.GOOGLE_DRIVE_FOLDER_LINK || ''}",
  SHEET_NAME: "${process.env.SHEET_NAME || 'Registrations'}",
  TEMPLATE_DOWNLOAD_URL: "${process.env.TEMPLATE_DOWNLOAD_URL || ''}",
  JOB_DESCRIPTION_URL: "${process.env.JOB_DESCRIPTION_URL || ''}"
};
`;

fs.writeFileSync('env.js', envContent);
console.log('✅ Successfully generated env.js with environment variables for Vercel deployment.');
